import type { Meta, StoryObj } from "@storybook/react";
import { Quote } from "./Quote";
import "assets/styles/index.css";

// More on how to set up stories at: https://storybook.js.org/docs/7.0/react/writing-stories/introduction
const meta = {
  title: "Content/Quote",
  component: Quote,
  tags: ["autodocs"],
} satisfies Meta<typeof Quote>;

export default meta;
type Story = StoryObj<typeof meta>;

// More on writing stories with args: https://storybook.js.org/docs/7.0/react/writing-stories/args
export const Default: Story = {
  args: {
    style: "border-blue-400",
    text: "Circumstances are the canvas of life, painted with the colors of our choices and actions. Each stroke, deliberate or spontaneous, contributes to the evolving masterpiece of our existence. Amid the seemingly chaotic blend of hues and textures, patterns emerge, echoing the harmonious rhythm of life. We are not mere spectators, but artists in our own right, imbuing meaning and beauty in every moment. Through the alchemy of our will, even the most mundane instant can be transformed into a timeless piece of art, a testament to our resilience, creativity, and love.",
    author: "Generated by ChatGPT",
  },
};
